In [1]:
import numpy as np


In [4]:
L = [1,2,3]
A = np.array([1,2,3])

In [7]:
for e in A:
    print(e)

1
2
3


In [8]:
for e in L:
    print(e)

1
2
3


In [9]:
L.append(4)

In [10]:
l

NameError: name 'l' is not defined

In [11]:
L

[1, 2, 3, 4]

In [12]:
A.append("4")

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [14]:
L=L+[5]

In [15]:
L

[1, 2, 3, 4, 5]

In [27]:
L2 = []
for e in L:
    L2.append(e*e)
print(L2)

[1, 4, 9, 16, 25]


In [25]:
L2

[1, 4, 9, 16, 25]

In [19]:
A+A

array([2, 4, 6])

In [20]:
L+L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [21]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [28]:
A**2

array([1, 4, 9])

In [29]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [30]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [31]:
np.sine(A)

AttributeError: module 'numpy' has no attribute 'sine'

In [32]:
np.add(A)

ValueError: invalid number of arguments

In [33]:
A+A

array([2, 4, 6])

In [34]:
A/A

array([ 1.,  1.,  1.])

In [35]:
A*A

array([1, 4, 9])

In [36]:
A-A

array([0, 0, 0])

In [ ]:
np.cosine(A)