In [1]:
# in machine learning columns called as attributes
# row is observation

In [26]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn import metrics

In [4]:
# create one dimensional series 
s = pd.Series([3,3,6,8,1,8])

In [5]:
s

0    3
1    3
2    6
3    8
4    1
5    8
dtype: int64

In [6]:
# top five series
s.head()

0    3
1    3
2    6
3    8
4    1
dtype: int64

In [5]:
# import csv file from online
ufo = pd.read_table('http://bit.ly/uforeports',sep=',')

In [10]:
ufo

City Colors Reported Shape Reported State  \
0                    Ithaca             NaN       TRIANGLE    NY   
1               Willingboro             NaN          OTHER    NJ   
2                   Holyoke             NaN           OVAL    CO   
3                   Abilene             NaN           DISK    KS   
4      New York Worlds Fair             NaN          LIGHT    NY   
5               Valley City             NaN           DISK    ND   
6               Crater Lake             NaN         CIRCLE    CA   
7                      Alma             NaN           DISK    MI   
8                   Eklutna             NaN          CIGAR    AK   
9                   Hubbard             NaN       CYLINDER    OR   
10                  Fontana             NaN          LIGHT    CA   
11                 Waterloo             NaN       FIREBALL    AL   
12                   Belton             RED         SPHERE    SC   
13                   Keokuk             NaN           OVAL    IA   
14                Ludington             NaN           DISK    MI   
15              Forest Home             NaN         CIRCLE    CA   
16              Los Angeles             NaN            NaN    CA   
17                Hapeville             NaN            NaN    GA   
18                   Oneida             NaN      RECTANGLE    TN   
19               Bering Sea             RED          OTHER    AK   
20                 Nebraska             NaN           DISK    NE   
21                      NaN             NaN            NaN    LA   
22                      NaN             NaN          LIGHT    LA   
23                Owensboro             NaN      RECTANGLE    KY   
24               Wilderness             NaN           DISK    WV   
25                San Diego             NaN          CIGAR    CA   
26               Wilderness             NaN           DISK    WV   
27                   Clovis             NaN           DISK    NM   
28               Los Alamos             NaN           DISK    NM   
29             Ft. Duschene             NaN           DISK    UT   
...                     ...             ...            ...   ...   
18211               Holyoke             NaN        DIAMOND    MA   
18212                Carson             NaN           DISK    CA   
18213              Pasadena           GREEN       FIREBALL    CA   
18214                Austin             NaN      FORMATION    TX   
18215              El Campo             NaN          OTHER    TX   
18216          Garden Grove          ORANGE          LIGHT    CA   
18217         Berthoud Pass             NaN       TRIANGLE    CO   
18218            Sisterdale             NaN        DIAMOND    TX   
18219          Garden Grove             NaN        CHEVRON    CA   
18220           Shasta Lake            BLUE           DISK    CA   
18221              Franklin             NaN           DISK    NH   
18222        Albrightsville             NaN          OTHER    PA   
18223            Greenville             NaN            NaN    SC   
18224               Eufaula             NaN           DISK    OK   
18225           Simi Valley             NaN      FORMATION    CA   
18226         San Francisco             NaN      FORMATION    CA   
18227         San Francisco             NaN       TRIANGLE    CA   
18228            Kingsville             NaN          LIGHT    TX   
18229               Chicago             NaN           DISK    IL   
18230           Pismo Beach             NaN           OVAL    CA   
18231           Pismo Beach             NaN           OVAL    CA   
18232                  Lodi             NaN            NaN    WI   
18233             Anchorage             RED        VARIOUS    AK   
18234              Capitola             NaN       TRIANGLE    CA   
18235        Fountain Hills             NaN            NaN    AZ   
18236            Grant Park             NaN       TRIANGLE    IL   
18237           Spirit Lake             NaN           DISK    IA   
18238      

In [12]:
ufo['State']

0        NY
1        NJ
2        CO
3        KS
4        NY
5        ND
6        CA
7        MI
8        AK
9        OR
10       CA
11       AL
12       SC
13       IA
14       MI
15       CA
16       CA
17       GA
18       TN
19       AK
20       NE
21       LA
22       LA
23       KY
24       WV
25       CA
26       WV
27       NM
28       NM
29       UT
         ..
18211    MA
18212    CA
18213    CA
18214    TX
18215    TX
18216    CA
18217    CO
18218    TX
18219    CA
18220    CA
18221    NH
18222    PA
18223    SC
18224    OK
18225    CA
18226    CA
18227    CA
18228    TX
18229    IL
18230    CA
18231    CA
18232    WI
18233    AK
18234    CA
18235    AZ
18236    IL
18237    IA
18238    WI
18239    WI
18240    FL
Name: State, dtype: object

In [6]:
# concatenate 
ufo['location'] = ufo.City + ',' + ufo.State

In [7]:
ufo.head()

City Colors Reported Shape Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

                  location  
0                Ithaca,NY  
1           Willingboro,NJ  
2               Holyoke,CO  
3               Abilene,KS  
4  New York Worlds Fair,NY

In [9]:
ufo.shape

(18241, 6)

In [10]:
ufo.dtypes

City               object
Colors Reported    object
Shape Reported     object
State              object
Time               object
location           object
dtype: object

In [12]:
ufo.describe()

City Colors Reported Shape Reported  State              Time  \
count     18216            2882          15597  18241             18241   
unique     6476              27             27     52             16145   
top     Seattle             RED          LIGHT     CA  11/16/1999 19:00   
freq        187             780           2803   2529                27   

          location  
count        18216  
unique        8029  
top     Seattle,WA  
freq           187

In [13]:
# remove a column
ufo.drop('Colors Reported', axis=1,inplace=True)


In [14]:
ufo.head()

City Shape Reported State             Time  \
0                Ithaca       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro          OTHER    NJ  6/30/1930 20:00   
2               Holyoke           OVAL    CO  2/15/1931 14:00   
3               Abilene           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair          LIGHT    NY  4/18/1933 19:00   

                  location  
0                Ithaca,NY  
1           Willingboro,NJ  
2               Holyoke,CO  
3               Abilene,KS  
4  New York Worlds Fair,NY

In [15]:
# remove more than one column
ufo.drop(['State','location'], axis=1,inplace=True)
ufo.head()

City Shape Reported             Time
0                Ithaca       TRIANGLE   6/1/1930 22:00
1           Willingboro          OTHER  6/30/1930 20:00
2               Holyoke           OVAL  2/15/1931 14:00
3               Abilene           DISK   6/1/1931 13:00
4  New York Worlds Fair          LIGHT  4/18/1933 19:00

In [16]:
ufo = pd.read_table('http://bit.ly/uforeports',sep=',')
ufo.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [20]:
#sort the value  

ufo.State.sort_values(ascending=True)

10454    AK
14421    AK
3511     AK
103      AK
2929     AK
12876    AK
106      AK
14422    AK
12875    AK
12874    AK
14401    AK
7791     AK
18116    AK
4399     AK
10262    AK
14405    AK
7714     AK
5576     AK
1765     AK
5135     AK
1845     AK
12165    AK
5553     AK
751      AK
2810     AK
5809     AK
5554     AK
12222    AK
17784    AK
7965     AK
         ..
9264     WY
9277     WY
12241    WY
6816     WY
12215    WY
1442     WY
1461     WY
14747    WY
7485     WY
15667    WY
14586    WY
14240    WY
12063    WY
7491     WY
14618    WY
16637    WY
12072    WY
10729    WY
6116     WY
7684     WY
5065     WY
378      WY
1177     WY
16594    WY
3328     WY
3326     WY
4866     WY
11333    WY
11490    WY
12079    WY
Name: State, dtype: object

In [21]:
ufo.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [22]:
ufo.sort_values('City').head()

City Colors Reported Shape Reported State              Time
1761   Abbeville             NaN           DISK    SC   12/10/1968 0:30
4553    Aberdeen             NaN       CYLINDER    WA   6/15/1981 22:00
16167   Aberdeen             NaN        VARIOUS    OH    3/29/2000 3:00
14703   Aberdeen             NaN       TRIANGLE    WA   9/30/1999 21:00
389     Aberdeen          ORANGE         CIRCLE    SD  11/15/1956 18:30

In [25]:
# sort more then one column
ufo.sort_values(['City','State']).head()

City Colors Reported Shape Reported State              Time
1761   Abbeville             NaN           DISK    SC   12/10/1968 0:30
2297    Aberdeen             NaN       TRIANGLE    MD    8/18/1972 1:30
9404    Aberdeen             NaN           DISK    MD   6/15/1996 13:30
16167   Aberdeen             NaN        VARIOUS    OH    3/29/2000 3:00
389     Aberdeen          ORANGE         CIRCLE    SD  11/15/1956 18:30

In [27]:
# array
x = np.array([2,3,5,7,9,])
x

array([2, 3, 5, 7, 9])

In [28]:
# what is the dimension
x.ndim

1

In [29]:
x.dtype

dtype('int32')

In [33]:
x[:4]

array([2, 3, 5, 7])

In [37]:
x[4>x]

array([2, 3])

In [35]:
# save data
np.save('x',x)

In [36]:
# load save data
np.load('x.npy')

array([2, 3, 5, 7, 9])

In [38]:
x

array([2, 3, 5, 7, 9])

# Scikit-Learn

 what is Scikit learn
    
    

Scity-Learn provides a range of supervised learning algorithm via a consisent interface in python

the library is focused on modeling data. it is not focused on loading, manupulating and sumuraizing data. For these feature 
    , refer to numpy and pandas

In [40]:
from sklearn import datasets
from sklearn import metrics

In [41]:
# support vector's classifier(SVC)
# support factorise machine(SVM)
from sklearn.svm import SVC

In [43]:
# load the iris dataset
ds = datasets.load_iris()

In [44]:
# fit a SVM model to thr data 

model = SVC()

In [45]:
model.fit(ds.data,ds.target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [46]:
print(model)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [47]:
# make predictions

expected = ds.target
predicted = model.predict(ds.data)


In [53]:
# summarize the fit of the model
s = metrics.classification_report(expected,predicted)

In [54]:
print(s)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       1.00      0.96      0.98        50
          2       0.96      1.00      0.98        50

avg / total       0.99      0.99      0.99       150



precision looks at the ratio of correct positive obsrvation

Recall is alsoknow as sensitivity or true positive rate. it's the ratio of correctly predicted positive event

F1 score is the weighted average of precision and recall. Therefore, this score take both false positive and false negative into account

# NLP(natural Language processing)

The ideas of NLP is to do some form of analysis, or processing, where the machine can understand, at least to some level, what the text mean, says or  implies 

tokenization: is a process of braking up a piece of text into many pieces, such as sentences and word. It works by separating word using space and punctuation

In [66]:
# Let's tokenize some words.

# tokenization: is a process of braking up a piece of text into many pieces, such as sentences and 

from nltk.tokenize import sent_tokenize
s = "I like udemy course."
sent_tokenize(s)

LookupError: 
**********************************************************************
  Resource 'tokenizers/punkt/english.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - 'C:\\Users\\ANSUSA/nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'D:\\SUBASH\\digitronix\\New folder\\nltk_data'
    - 'D:\\SUBASH\\digitronix\\New folder\\lib\\nltk_data'
    - 'C:\\Users\\ANSUSA\\AppData\\Roaming\\nltk_data'
    - ''
**********************************************************************